# Generated by Django 2.0.2 on 2018-02-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
                ('practice_location', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('BA', 'Backache'), ('CR', 'Cranial Osteopathy'), ('PE', 'Pediatrics Osteopathy'), ('PR', 'Pregnancy Osteopathy'), ('SP', 'Sport Osteopathy'), ('ST', 'Structural Osteopathy'), ('TO', 'Torticollis'), ('VI', 'Visceral Osteopathy')], max_length=2, verbose_name='Specialization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
