# Generated by Django 2.0.2 on 2018-02-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20180207_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Specialization', verbose_name='Specialization'),
        ),
    ]
